blank_issues_enabled: false
contact_links:
  - name: Have a Question or Need 1-on-1 support?
    url: mailto:support@aetherassembly.org
    about: Shoot us an email and we'll get back to you within twenty-four (24) hours to fourty-eight (48) hours from your message. Please include as much detail as possible, including screenshots if applicable.
